### ISSUE TITLE
No modile named `model`

### ISSUE THREAD

**Issue by arianaa30** [gyglim/video2gif_code#11]
I install the code on the main path thorugh:
`python setup.py install`
But I don't know why this error when doing `import video2gif`. Looks like it can not find the model.py file which was already installed. 

```
>>> import video2gif
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\user\Downloads\video2gif_code\video2gif\__init__.py", line 18, in <module>
    import model
ModuleNotFoundError: No module named 'model'
```

**Comment by archywillhe** [comment]
got the same error too; on mac though

**Comment by harishyvs** [comment]
just add the video2gif folder to your PYTHONPATH.

**Comment by BeyondHeaven** [comment]
I have the same issue.
I think the model path should be `video2gif_code/build/lib/video2gif/model.py`
I add `sys.path.append("../build/lib/video2gif/")` in `video2gif_code/video2gif/__init__.py`, but it doesn't work.
Any ideas?
