### ISSUE TITLE
the version of Lasagne and Theano

### ISSUE THREAD

**Issue by IsanHu** [gyglim/video2gif_code#4]
I tried serval version of Lasagne and Theano including the dev version, but always encounte package dependency issues. eg:
```
Traceback (most recent call last):
  File "test.py", line 2, in <module>
    import video2gif
  File "/Users/isan/Dev/ML/video2gif/video2gif/__init__.py", line 18, in <module>
    import model
  File "/Users/isan/Dev/ML/video2gif/video2gif/model.py", line 8, in <module>
    from lasagne.layers.shape import PadLayer
  File "/Users/isan/.virtualenvs/video2gif/lib/python2.7/site-packages/lasagne/__init__.py", line 19, in <module>
    from . import layers
  File "/Users/isan/.virtualenvs/video2gif/lib/python2.7/site-packages/lasagne/layers/__init__.py", line 7, in <module>
    from .pool import *
  File "/Users/isan/.virtualenvs/video2gif/lib/python2.7/site-packages/lasagne/layers/pool.py", line 6, in <module>
    from theano.tensor.signal import downsample
ImportError: cannot import name downsample

Please post a working version number, Thanks a lot

**Comment by gyglim** [comment]
that looks like your Theano version is too old. Since it happens when importing Lasagne, it does not seem to be a problem with this code. I suggest installing the bleeding edge version as described here:
https://lasagne.readthedocs.io/en/latest/user/installation.html

please let me know if this fixes the problem

**Comment by beset** [comment]
**Still doesn't work :**
```
requires GPU support -- see http://lasagne.readthedocs.org/en/latest/user/installation.html#gpu-support
Loaded config file from /home/3isan333/Code/video2gif_code/video2gif/config.ini
Load weights and compile model...
Use slow network implementation (without cuDNN)
Traceback (most recent call last):
  File "test.py", line 12, in <module>
    score_function = video2gif.get_prediction_function()
  File "/home/3isan333/Code/video2gif_code/video2gif/__init__.py", line 42, in get_prediction_function
    net= model.build_model(batch_size=2)
  File "/home/3isan333/Code/video2gif_code/video2gif/model.py", line 46, in build_model
    net['pool1']  = lasagne.layers.pool.Pool3Layer(net['conv1a'],pool_size=(1,2,2),stride=(1,2,2))
AttributeError: 'module' object has no attribute 'Pool3Layer'
```


**you can check my system**
```
Linux version 4.4.0-66-generic (buildd@lgw01-28) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) )
```



and all my python packages:
```
appdirs (1.4.3)
cycler (0.10.0)
decorator (4.0.11)
functools32 (3.2.3.post2)
imageio (2.1.2)
Lasagne (0.2.dev1)
matplotlib (2.0.0)
moviepy (0.2.3.1)
networkx (1.11)
numpy (1.12.1)
olefile (0.44)
packaging (16.8)
pandas (0.19.2)
Pillow (4.1.0)
pip (9.0.1)
pyparsing (2.2.0)
python-dateutil (2.6.0)
pytz (2017.2)
PyWavelets (0.5.2)
scikit-image (0.13.0)
scipy (0.19.0)
setuptools (34.4.0)
six (1.10.0)
subprocess32 (3.2.7)
Theano (0.9.0)
tqdm (4.11.2)
wheel (0.29.0)
```

**Comment by IsanHu** [comment]
It's because my device is cpu and I didn't use your version of Lasagne

**Comment by gyglim** [comment]
if you want to run it on CPU: we also recently added 3D Convolutions and Pooling to the dev version of Lasagne, see https://github.com/Lasagne/Lasagne/pull/791
it is however calles `Pool3DLayer`, while in my model definition it is calles `Pool3Layer`. So you'd need to rename it there. I will rename it in the main repo once I get around to it

**Comment by IsanHu** [comment]
Does Pool3Layer do any bad?  The demo in tutorial has been running for a long time, i don't wanna stop it. By the way how long dose it take to finish with 2 vcpus and 8G ram ?

**Comment by gyglim** [comment]
it's just very slow on CPU. Maybe a few minutes

**Comment by IsanHu** [comment]
it's been 100 minutes..... what's wrong...

**Comment by IsanHu** [comment]
![test](https://cloud.githubusercontent.com/assets/3689943/24899549/496b4594-1ed3-11e7-9f08-4884a56e7e3d.png)

it's been here for like a century ...

**Comment by vasusharma** [comment]
I'm having the same issue. Takes too long.
Your version of Lasagne seems not to support the CUDNN I have installed and the bleeding edge lasagne doesnt have Pool3Layer.
Not sure what to do?

**Comment by gyglim** [comment]
Does it say: "Use slow network implementation (without cuDNN)"?
that means your theano config is incorrect, see:
https://github.com/gyglim/video2gif_code/blob/master/video2gif/model.py#L25
and
http://deeplearning.net/software/theano/library/config.html#envvar-THEANO_FLAGS
you need to set device to `cuda` or `gpu`

**Comment by vasusharma** [comment]
That helped :)
Now the error of running in slow non cudnn mode is gone but now I am having errors importing Conv3DDNNLayer. 

```
NameError: global name 'Conv3DDNNLayer' is not defined
>>> from lasagne.layers.dnn import Conv3DDNNLayer
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/Lasagne-0.2.dev1-py2.7.egg/lasagne/layers/dnn.py", line 14, in <module>
    "requires GPU support -- see http://lasagne.readthedocs.org/en/"
ImportError: requires GPU support -- see http://lasagne.readthedocs.org/en/latest/user/installation.html#gpu-support
```

However my GPU support is enabled. It passes all the tests mentioned at : http://lasagne.readthedocs.org/en/latest/user/installation.html#gpu-support

```
THEANO_FLAGS=device=gpu python -c "import theano; print(theano.sandbox.cuda.device_properties(0))"
WARNING (theano.sandbox.cuda): The cuda backend is deprecated and will be removed in the next release (v0.10).  Please switch to the gpuarray backend. You can get more information about how to switch at this URL:
 https://github.com/Theano/Theano/wiki/Converting-to-the-new-gpu-back-end%28gpuarray%29

Using gpu device 0: TITAN X (Pascal) (CNMeM is disabled, cuDNN 5110)
{'major': 6, 'tccDriver': 0, 'kernelExecTimeoutEnabled': 1, 'deviceOverlap': 1, 'driverVersion': 8000, 'warpSize': 32, 'concurrentKernels': 1, 'maxThreadsPerBlock': 1024, 'computeMode': 0, 'canMapHostMemory': 1, 'maxGridSize2': 65535, 'maxGridSize1': 65535, 'maxGridSize0': 2147483647, 'integrated': 0, 'minor': 1, 'ECCEnabled': 0, 'runtimeVersion': 8000, 'textureAlignment': 512, 'multiProcessorCount': 28, 'clockRate': 1531000, 'totalConstMem': 65536, 'name': 'TITAN X (Pascal)', 'memPitch': 2147483647, 'maxThreadsDim1': 1024, 'maxThreadsDim0': 1024, 'maxThreadsDim2': 64, 'coresCount': -28, 'sharedMemPerBlock': 49152, 'regsPerBlock': 65536}

```

and 

```
python -c "from theano.sandbox.cuda.dnn import dnn_available as d; print(d() or d.msg)"
Using cuDNN version 5110 on context None
Mapped name None to device cuda2: TITAN X (Pascal) (0000:09:00.0)
WARNING (theano.sandbox.cuda): The cuda backend is deprecated and will be removed in the next release (v0.10).  Please switch to the gpuarray backend. You can get more information about how to switch at this URL:
 https://github.com/Theano/Theano/wiki/Converting-to-the-new-gpu-back-end%28gpuarray%29

Using gpu device 0: TITAN X (Pascal) (CNMeM is disabled, cuDNN 5110)
True
```

Any suggestions?

**Comment by gyglim** [comment]
you also need to set
`optimizer_including=cudnn`
in the theano flags so that cuDNN is enabled

Also see
http://dhaneshr.net/2015/09/10/setting-up-cudnn-and-theano-on-ubuntu-14-04-and-15-10/

**Comment by vasusharma** [comment]
Set the flag and also followed the tutorial in the link. My CuDNN install passes all the tests but I am still getting the same error as before :(
